language: node_js
sudo: false
node_js:
  - '6'

addons:
  apt:
    sources:
      # needed to install g++ that is used by npms's native modules
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  except:
    - g3_v2_0

after_script:
  - npm run report-cov
